phpmd:
  # Add here other or more rulesets (comma separated)
  ruleset: codesize
phpcs:
  # Add here your own standard (path) or set a default like PSR1
  standard: PSR1
forbidden:
  # Add here methods that not allowed to commit like var_dump
  methods: ["evalMethod", "printEvalResults","print_r"]
phpunit:
  configuration: phpunit.xml
